version: "3.8"

services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=4ser
      - MONGO_INITDB_ROOT_PASSWORD=m0ngo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro